version: '3.8'
services:
  api:
    image: ${REGISTRY}/${REPO_OWNER}/${API_IMAGE_NAME}:latest
    container_name: onforkhub-api
    restart: unless-stopped
    ports:
      - "0.0.0.0:9000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HOSTFILTERING_ALLOWEDHOSTS=*
      - COMPlus_GCConserveMemory=9
      - COMPlus_HeapHardLimit=500000000
      - DOTNET_GCHeapHardLimit=500000000
    deploy:
      resources:
        limits:
          memory: 800M
          cpus: '0.8'
        reservations:
          memory: 200M
          cpus: '0.2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge