services:
  api:
    image: ghcr.io/rondineleg/onforkhub-api:latest
    container_name: onforkhub-api
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HOSTFILTERING_ALLOWEDHOSTS=*
      - COMPlus_GCConserveMemory=9
      - COMPlus_HeapHardLimit=300000000
      - DOTNET_GCHeapHardLimit=300000000
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.4'
        reservations:
          memory: 100M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    image: ghcr.io/rondineleg/onforkhub-web:latest
    container_name: onforkhub-web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HOSTFILTERING_ALLOWEDHOSTS=*
      - COMPlus_GCConserveMemory=9
      - COMPlus_HeapHardLimit=300000000
      - DOTNET_GCHeapHardLimit=300000000
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.4'
        reservations:
          memory: 100M
          cpus: '0.1'
    depends_on:
      - api

networks:
  default:
    driver: bridge
