version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: src/Presentations/OnForkHub.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
        APP_UID: 1000
    container_name: onforkhub-api
    restart: unless-stopped
    ports:
      - "9000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - onforkhub-network

  web:
    build:
      context: .
      dockerfile: src/Presentations/OnForkHub.Web/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
        APP_UID: 1000
    container_name: onforkhub-web
    restart: unless-stopped
    ports:
      - "3000:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - api
    networks:
      - onforkhub-network

networks:
  onforkhub-network:
    name: onforkhub-network
    external: true
