global using System.Net;
global using Microsoft.Azure.Cosmos;
global using Microsoft.EntityFrameworkCore;
global using OnForkHub.Core.Entities;
global using OnForkHub.Core.Entities.Base;
global using OnForkHub.Core.Interfaces.Repositories;
global using OnForkHub.Core.Requests;
global using OnForkHub.Persistence.Contexts.Base;
global using OnForkHub.Persistence.Exceptions;
