global using Asp.Versioning;
global using Asp.Versioning.Builder;
global using Microsoft.AspNetCore.Mvc;
global using OnForkHub.Api.Configuration;
global using OnForkHub.Api.Endpoints.Base;
global using OnForkHub.Core.Entities;
global using OnForkHub.Core.Entities.Base;
global using OnForkHub.Core.Interfaces.Repositories;
global using OnForkHub.Core.Requests;
