services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 9443:9443

      - 9000:9000

    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '0.15'
        reservations:
          memory: 50M
          cpus: '0.05'
    volumes:
      - ./custom.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx

      - /etc/ssl/zerossl:/etc/ssl/zerossl:ro
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    networks:
      - onforkhub-network
    depends_on:
      onforkhub-api:
        condition: service_healthy
      onforkhub-web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  onforkhub-api:
    image: ghcr.io/rondineleg/onforkhub-api:latest
    container_name: onforkhub-api
    restart: unless-stopped
    expose:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_REDIRECTION_ENABLED=false
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - COMPlus_GCConserveMemory=1
      - COMPlus_HeapHardLimit=400000000
      - DOTNET_GCHeapHardLimit=400000000
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_RUNNING_IN_CONTAINER=true
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
        reservations:
          memory: 100M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./logs/api:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - onforkhub-network

  onforkhub-web:
    image: ghcr.io/rondineleg/onforkhub-web:latest
    container_name: onforkhub-web
    restart: unless-stopped
    depends_on:
      onforkhub-api:
        condition: service_healthy
    expose:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.3'
        reservations:
          memory: 50M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./logs/web:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - onforkhub-network

networks:
  onforkhub-network:
    name: onforkhub-network
    driver: bridge
