version: '3.8'

networks:
  onforkhub-network:
    driver: bridge

services:
  onforkhub-api:
    image: ghcr.io/rondineleG/onforkhub-api:latest
    container_name: onforkhub-api
    restart: unless-stopped
    networks:
      - onforkhub-network
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ASPNETCORE_HTTPSREDIRECTION_ENABLED=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health", "||", "curl", "-f", "http://localhost:80/", "||", "exit", "1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  onforkhub-web:
    image: ghcr.io/rondineleG/onforkhub-web:latest
    container_name: onforkhub-web
    restart: unless-stopped
    networks:
      - onforkhub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9443:9443"
    volumes:
      - ./custom.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/zerossl:/etc/ssl/zerossl:ro
      - /var/log/nginx:/var/log/nginx
    networks:
      - onforkhub-network
    depends_on:
      onforkhub-api:
        condition: service_healthy
      onforkhub-web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
