services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ./custom.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - my-network

networks:
  my-network:
    external: true