#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
export HUSKY_GIT_PARAMS="$BRANCH_NAME"

dotnet run --project src/Shared/OnForkHub.Scripts/OnForkHub.Scripts.csproj pr-create