#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
export GIT_FLOW_BRANCH="$BRANCH_NAME"

dotnet run --project src/Shared/OnForkHub.Scripts/OnForkHub.Scripts.csproj