name: Auto Deploy to VPS

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4
        
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          timeout: 60s
          command_timeout: 20m
          script: |
            mkdir -p ~/onforkhub-deploy/logs
            cd ~/onforkhub-deploy
            docker compose down --remove-orphans || true
            find . -maxdepth 1 ! -name 'logs' ! -name '.' ! -name '..' -exec rm -rf {} +
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Copy deployment files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".deploy/*"
          target: "~/onforkhub-deploy"
          strip_components: 1
          timeout: 60s

      - name: Start services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/onforkhub-deploy
            chmod +x *.sh
            ./start-services.sh

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/onforkhub-deploy
            docker ps
            echo "Container logs:"
            docker logs onforkhub-api --tail 10
            docker logs onforkhub-web --tail 10
            docker logs reverse-proxy --tail 10
