name: Build Docker Images
on:
  workflow_dispatch:
  push:
    branches:
      - dev
env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: onforkhub-api
  WEB_IMAGE_NAME: onforkhub-web
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    outputs:
      image_tag: ${{ github.sha }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set lowercase repository owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile.OnForkHub.Api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.API_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.API_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile.OnForkHub.Web
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.WEB_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.WEB_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "$SSH_KEY"
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa $SSH_HOST >> ~/.ssh/known_hosts

      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
        run: |
          ssh $SSH_USER@$SSH_HOST "mkdir -p ~/onforkhub"
          
          cat > docker-compose.yml << EOF
          version: '3.8'
          services:
            api:
              image: ghcr.io/rondineleg/onforkhub-api:${IMAGE_TAG}
              container_name: onforkhub-api
              restart: unless-stopped
              ports:
                - "9000:9000"
              environment:
                - ASPNETCORE_ENVIRONMENT=Production
                - ASPNETCORE_URLS=http://+:9000
              networks:
                - onforkhub-network
            web:
              image: ghcr.io/rondineleg/onforkhub-web:${IMAGE_TAG}
              container_name: onforkhub-web
              restart: unless-stopped
              ports:
                - "80:80"
              environment:
                - ASPNETCORE_ENVIRONMENT=Production
                - ASPNETCORE_URLS=http://+:80
              depends_on:
                - api
              networks:
                - onforkhub-network
          networks:
            onforkhub-network:
              name: onforkhub-network
          EOF

          scp docker-compose.yml $SSH_USER@$SSH_HOST:~/onforkhub/
          
          ssh $SSH_USER@$SSH_HOST "cd ~/onforkhub && \
            echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin && \
            docker-compose down --volumes --remove-orphans && \
            docker-compose pull && \
            docker-compose up -d && \
            docker image prune -f"
