name: Manual Deploy
on:
 workflow_dispatch:
   inputs:
     branch:
       description: 'Branch to deploy'
       required: true
       type: choice
       options:
         - dev
         - main
         - feature/*

env:
 REGISTRY: ghcr.io
 API_IMAGE_NAME: onforkhub-api
 WEB_IMAGE_NAME: onforkhub-web
 DOCKER_BUILDKIT: 1

jobs:
 deploy:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
   
   steps:
     - uses: actions/checkout@v4
     
     - name: Deploy to VPS
       uses: appleboy/ssh-action@v1.0.0
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           mkdir -p ~/onforkhub-deploy/logs
           cd ~/onforkhub-deploy
           docker compose down --remove-orphans || true
           find . -maxdepth 1 ! -name 'logs' ! -name '.' ! -name '..' -exec rm -rf {} +
           echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

     - name: Copy deployment files
       uses: appleboy/scp-action@v0.1.7
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         source: ".deploy/*"
         target: "~/onforkhub-deploy"
         strip_components: 1

     - name: Start services
       uses: appleboy/ssh-action@v1.0.0
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           cd ~/onforkhub-deploy
           chmod +x *.sh
           ./start-services.sh
