name: Deploy to VPS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Docker Images"] 
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy with rsync
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          # Teste da conexão SSH
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'echo "Connected successfully"'
          
          # Copiar arquivos e executar
          scp -r .deploy/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/onforkhub-deploy/
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            cd ~/onforkhub-deploy && \
            chmod +x *.sh && \
            ./start-services.sh
          '

      - name: Verify deployment
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'docker ps'
