name: Deploy to VPS (Manual)
run-name: Manual VPS Deploy by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  deploy:
    name: VPS Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/onforkhub-deploy/logs
            cd ~/onforkhub-deploy
            docker compose down --remove-orphans
            rm -rf ./*

      - name: Copy Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".deploy/*"
          target: "~/onforkhub-deploy"
          strip_components: 1

      - name: Start Services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/onforkhub-deploy
            chmod +x *.sh
            ./start-services.sh
